### PR TITLE
fix: skip steps fix.

### PR DESCRIPTION
**Pull request by ankitrawatgit**

### CODE REVIEW

**Comment by RohitVerma882** [comment]
Both these methods are available in step 9 bro.
These two are not in different steps no

**Comment by ankitrawatgit** [comment]
> Both these methods are available in step 9 bro. These two are not in different steps no.

So after of running the skip command of step 8, we will have to run the command from step 9 also!!. 
it's required to show that step 9 is also skiped when the step 8's OR command execute.

**Comment by RohitVerma882** [comment]
> > Both these methods are available in step 9 bro. These two are not in different steps no.
> 
> So after of running the skip command of step 8, we will have to run the command from step 9 also!!. it's required to show that step 9 is also skiped when the step 8's OR command execute.
To aap es step ko bhi ek number de do.
example:
10. (skip step 8 & 9)
``` console
mi-fastboot oem-unlock <token>
```

**Comment by RohitVerma882** [comment]
> > > Both these methods are available in step 9 bro. These two are not in different steps no.
> > 
> > 
> > So after of running the skip command of step 8, we will have to run the command from step 9 also!!. it's required to show that step 9 is also skiped when the step 8's OR command execute.
> > To aap es step ko bhi ek number de do.
> > example:
> 
> 10. (skip step 8 & 9)
> 
> ```
> mi-fastboot oem-unlock <token>
> ```

To aap es step ko bhi ek number de do.
example:

**Comment by ankitrawatgit** [comment]
> To aap es step ko bhi ek number de do.
> example:
> 10. (skip step 8 & 9)
> ``` console
> mi-fastboot oem-unlock <token>
> ```
> 

Nhi aase he kr do, shi ha

**Comment by ankitrawatgit** [comment]
bro merge it.

**Pull request closed without merging**
